front:
	npm run start

front-docker-build:
	docker-compose -f docker-compose.build.yml up --build

front-docker-build-down:
	docker-compose -f docker-compose.build.yml down

front-docker-prod:
	docker-compose -f docker-compose.prod.yml up

front-docker-prod-down:
	docker-compose -f docker-compose.prod.yml down
