version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${SEQUELIZE__DATABASE}
      MYSQL_USER: ${SEQUELIZE__USERNAME}
      MYSQL_PASSWORD: ${SEQUELIZE__PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE__ROOT_PASSWORD}
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/db/var/lib/mysql:/var/lib/mysql

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - 80:5000
    environment:
      SEQUELIZE__HOST: db
    volumes:
      - ./backend/.env:/app/.env
      - ./docker.backend.run.sh:/app/docker.backend.run.sh
    command: sh docker.backend.run.sh
