name: Deploy to Docker Hub

on:
  push:
    branches: ["2022-08-30-14-55"]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB__LOGIN }}
          password: ${{ secrets.DOCKER_HUB__PASSWORD }}

      - name: docker build and docker push
        uses: docker/build-push-action@v3.0.0
        with:
          file: Dockerfile
          tags: pavelinnokentevichgalanin/6sem-practice-backend:latest
          push: true
